version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: rq worker --with-scheduler gemini
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development