version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: "postgres:alpine"
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./db/postgresDB:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - ":6379"

  worker:
    build: .
    command: rq worker --with-scheduler gemini
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    env_file:
      - .env

  web2:
    build: ../event-tracker-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      